### PR TITLE
Better access

### PR DESCRIPTION
**Pull request by agentrickard**
This PR does a few things:

- Moves the access check to a route service rather than the Controller.
- Sets an `enabled` config item so that you can disable the module in `settings.php` or config split.
- Sets a default header value of `drupalKey` from your `cypress.json` config file.
- Allows you to override that default key by editing settings.php and your `commands.js` file.
- Documents all of the above.

### CODE REVIEW

**Comment by agentrickard** [comment]
@byrond This change requires that we add a `drupalKey` to cypress.json -or- use a private key.

I suppose we could disable key handling on Circle if we want. That would require a logic change, though. Probably best to add `drupalKey: foo` to the Circle's cupress.json file.

**Comment by byrond** [comment]
I can confirm that this fails on CircleCI when attempting to use `grantDrupalPermission()` without having the key:
image

**Comment by byrond** [comment]
> @byrond This change requires that we add a `drupalKey` to cypress.json -or- use a private key.
> 
> I suppose we could disable key handling on Circle if we want. That would require a logic change, though. Probably best to add `drupalKey: foo` to the Circle's cupress.json file.

We can configure a key that will only be used on CircleCI by using separate `cypress.json` and `settings.php` files on that environment. I believe that will be sufficient.

**Comment by byrond** [comment]
@agentrickard I had to make two changes to get this to work:
* As mentioned above, the config value was not being used for `key_file`
* The `getDrupalKey()` function was not being called from the helper methods, so `"cypress"` was always used for the header.

**Comment by agentrickard** [comment]
Yeah. those are probably oversights from copy/paste during testing. This is ready-to-merge when you are.

**Pull request merged**
